---
abstract: 'Object for copyright years changing in POD.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-CopyrightYears
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0
  Error::Pure: 0.3
  Pod::Abstract: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Pod-CopyrightYears/issues
  homepage: https://github.com/michal-josef-spacek/Pod-CopyrightYears
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Pod-CopyrightYears
version: '0.01'
